### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by kd8azz** [google/protobuf-dt#7]
I followed the directions on https://github.com/google/protobuf-dt/blob/master/README.md

Error Message:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Protocol Buffer Editor 2.3.2.201609161849 (com.google.eclipse.protobuf.feature.group 2.3.2.201609161849)
  Missing requirement: Protocol Buffer Descriptor Editor 2.3.2.201609161849 (com.google.eclipse.protobuf 2.3.2.201609161849) requires 'bundle org.eclipse.core.resources [3.11.0,4.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Protocol Buffer Editor 2.3.2.201609161849 (com.google.eclipse.protobuf.feature.group 2.3.2.201609161849)
    To: com.google.eclipse.protobuf [2.3.2.201609161849]

System Details:
Ubuntu GNOME 16.04.1 LTS
Eclipse Mars.2 Release (4.5.2)

**Comment by habelson** [comment]
I am having the same problem

Windows 8.1
Eclipse Mars.1 Release (4.5.1)

**Comment by paulvi** [comment]
Reading comments at http://marketplace.eclipse.org/content/protobuf-dt , I see there was a update site problem before.

This issue should be closed, I guess.
As recent problems are likely to be network related.

@habelson Have you succeeded later?

**Comment by habelson** [comment]
I was not able to get it to work for Mars, but after upgrading to Neon on the same day, it worked just fine.

**Comment by atrookey** [comment]
As of version 2.3.0 the Protobuf Editor requires Neon or greater.   I'll make a note of the requirement in the README.

**Comment by mhiebenga** [comment]
Currenty using Eclipse Neon2. It is not possible to install the plug in:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Protocol Buffer Editor 2.3.2.201609161849 (com.google.eclipse.protobuf.feature.group 2.3.2.201609161849)
  Missing requirement: Protocol Buffer Editor 2.3.2.201609161849 (com.google.eclipse.protobuf.feature.group 2.3.2.201609161849) requires 'org.antlr.runtime 0.0.0' but it could not be found
